export const policies = [
  {
    id: 'CB_HOUSING_001',
    title: '충북 청년 월세 지원',
    category: '주거 지원',
    region: '충북 전역',
    benefit: '월 최대 20만원',
    period: '상시 확인',
    eligibility: '만 19~39세 무주택 청년',
    summary: '청년의 주거비 부담을 낮추기 위해 월세 일부를 지원합니다.',
    detail: '월세 거주 청년에게 실제 납부 임대료 일부를 지원하는 정책입니다.',
    requiredDocuments: [
      '신청서',
      '주민등록등본',
      '임대차계약서',
      '월세 납부 증빙',
      '소득 증빙 서류',
    ],
    agency: '충청북도 또는 관할 시군',
    sourceName: '충북 청년포털',
    sourceUrl: 'https://www.chungbuk.go.kr',
    lastChecked: '2026-08-11',
    status: '확인 필요',
    requiredInputs: [
      'age',
      'region',
      'housingType',
      'monthlyRent',
      'isHouseOwner',
      'income',
    ],
  },
  {
    id: 'CB_JOB_001',
    title: '청년도전 지원사업',
    category: '일자리 지원',
    region: '충북 전역',
    benefit: '취업역량 강화 프로그램 및 참여수당',
    period: '사업별 상이',
    eligibility: '구직단념 청년 또는 취업 준비 청년',
    summary:
      '취업 준비 상태의 청년에게 상담, 교육, 프로그램 참여 기회를 제공합니다.',
    detail:
      '취업 준비 또는 구직 상담이 필요한 청년을 위한 일자리 지원 정책입니다.',
    requiredDocuments: ['신청서', '신분증', '구직 상태 확인 서류'],
    agency: '충청북도 일자리지원센터',
    sourceName: '충북 청년포털',
    sourceUrl: 'https://www.chungbuk.go.kr',
    lastChecked: '2026-08-11',
    status: '확인 필요',
    requiredInputs: ['age', 'employmentStatus', 'job'],
  },
  {
    id: 'CB_JOB_002',
    title: '충청북도 일자리지원센터 운영',
    category: '일자리 지원',
    region: '충북 전역',
    benefit: '취업 상담 및 구인구직 매칭',
    period: '상시 확인',
    eligibility: '충북 내 취업을 희망하는 구직자',
    summary:
      '충북 내 일자리 상담, 구인구직 매칭, 입사지원 컨설팅을 제공합니다.',
    detail:
      '희망 직무와 추천 지역을 기준으로 일자리센터 상담을 연결할 수 있습니다.',
    requiredDocuments: ['상담 신청서', '이력서'],
    agency: '충청북도 일자리지원센터',
    sourceName: '충북 청년포털',
    sourceUrl: 'https://www.chungbuk.go.kr',
    lastChecked: '2026-08-11',
    status: '확인 필요',
    requiredInputs: ['job', 'region', 'employmentStatus'],
  },
  {
    id: 'CJ_JOB_001',
    title: '청주형 내일공감 일자리사업',
    category: '일자리 지원',
    region: '청주시',
    benefit: '청년 근속 인센티브 및 기업 인건비 지원',
    period: '공고 확인 필요',
    eligibility: '청주시 거주 미취업 청년',
    summary: '청주시 관내 기업 취업과 근속을 지원하는 일자리 사업입니다.',
    detail:
      '청주 취업 희망자와 관내 기업을 연결하는 청년 일자리 지원 정책입니다.',
    requiredDocuments: ['신청서', '주민등록등본', '미취업 확인 자료'],
    agency: '청주시',
    sourceName: '충북 청년포털',
    sourceUrl: 'https://www.chungbuk.go.kr',
    lastChecked: '2026-08-11',
    status: '확인 필요',
    requiredInputs: ['age', 'region', 'employmentStatus'],
  },
  {
    id: 'CH_HOUSING_001',
    title: '충주시 청년 신혼부부 월세 지원',
    category: '주거 지원',
    region: '충주시',
    benefit: '월세 일부 지원',
    period: '공고 확인 필요',
    eligibility: '충주시 거주 무주택 청년 신혼부부',
    summary: '청년 신혼부부의 주거비 부담 완화와 지역 정착을 돕습니다.',
    detail:
      '혼인 기간, 무주택 여부, 월세 거주 여부 등 세부 조건 확인이 필요합니다.',
    requiredDocuments: [
      '신청서',
      '혼인관계증명서',
      '주민등록등본',
      '임대차계약서',
    ],
    agency: '충주시',
    sourceName: '충북 청년포털',
    sourceUrl: 'https://www.chungbuk.go.kr',
    lastChecked: '2026-08-11',
    status: '확인 필요',
    requiredInputs: [
      'age',
      'region',
      'householdType',
      'housingType',
      'isHouseOwner',
    ],
  },
  {
    id: 'CH_STARTUP_001',
    title: '청년 소상공인 창업점포 임차료 지원',
    category: '창업 지원',
    region: '충주시',
    benefit: '점포 임차료 일부 지원',
    period: '공고 확인 필요',
    eligibility: '충주시 소재 청년 소상공인',
    summary: '초기 청년 창업자의 점포 임차료 부담을 줄이는 정책입니다.',
    detail: '사업장 지역, 사업자등록 기간, 점포 임차 여부 확인이 필요합니다.',
    requiredDocuments: [
      '신청서',
      '사업자등록증',
      '임대차계약서',
      '임차료 납부 증빙',
    ],
    agency: '충주시',
    sourceName: '충북 청년포털',
    sourceUrl: 'https://www.chungbuk.go.kr',
    lastChecked: '2026-08-11',
    status: '확인 필요',
    requiredInputs: ['age', 'region', 'startupInterest'],
  },
  {
    id: 'OK_HOUSING_001',
    title: '옥천군 청년 전세대출금 이자 지원',
    category: '주거 지원',
    region: '옥천군',
    benefit: '전세대출금 잔액의 3%, 연 최대 200만원',
    period: '공고 확인 필요',
    eligibility: '옥천군 거주 또는 전입 희망 만 19~39세 청년',
    summary: '옥천군 청년의 전세대출 이자 부담을 줄이는 정착 지원 정책입니다.',
    detail:
      '전세대출 여부, 대출 잔액, 자녀 여부 등 세부 조건 확인이 필요합니다.',
    requiredDocuments: [
      '신청서',
      '주민등록등본',
      '전세계약서',
      '대출잔액증명서',
    ],
    agency: '옥천군',
    sourceName: '옥천군',
    sourceUrl: 'https://www.oc.go.kr',
    lastChecked: '2026-08-11',
    status: '확인 필요',
    requiredInputs: ['age', 'region', 'housingType', 'loanBalance'],
  },
  {
    id: 'OK_HOUSING_002',
    title: '옥천군 청년월세 지원',
    category: '주거 지원',
    region: '옥천군',
    benefit: '월세 일부 지원',
    period: '공고 확인 필요',
    eligibility: '옥천군 거주 만 19~39세 무주택 청년',
    summary: '옥천군 거주 청년의 월세 부담을 줄이는 주거 지원 정책입니다.',
    detail: '소득, 무주택, 월세 거주 여부 등 세부 조건 확인이 필요합니다.',
    requiredDocuments: [
      '신청서',
      '주민등록등본',
      '임대차계약서',
      '소득 증빙 서류',
    ],
    agency: '옥천군',
    sourceName: '옥천군 청년포털',
    sourceUrl: 'https://www.oc.go.kr',
    lastChecked: '2026-08-11',
    status: '확인 필요',
    requiredInputs: ['age', 'region', 'housingType', 'isHouseOwner', 'income'],
  },
  {
    id: 'GS_HOUSING_001',
    title: '청년 농촌보금자리 조성사업',
    category: '주거 지원',
    region: '괴산군',
    benefit: '농촌 정착형 주거 지원',
    period: '공고 확인 필요',
    eligibility: '귀농·귀촌 또는 농촌 정착 희망 청년',
    summary: '청년의 농촌 정착을 돕기 위한 주거 기반 지원 정책입니다.',
    detail:
      '농촌 거주 선호, 가족·보육 고려 여부, 괴산군 관심 여부가 추천에 반영됩니다.',
    requiredDocuments: ['신청서', '정착 계획서', '주민등록등본'],
    agency: '괴산군',
    sourceName: '충북 청년포털',
    sourceUrl: 'https://www.chungbuk.go.kr',
    lastChecked: '2026-08-11',
    status: '확인 필요',
    requiredInputs: ['age', 'region', 'ruralInterest'],
  },
  {
    id: 'GS_STARTUP_001',
    title: '괴산형 청년창업 지원사업',
    category: '창업 지원',
    region: '괴산군',
    benefit: '로컬 창업 사업화 지원',
    period: '공고 확인 필요',
    eligibility: '괴산군 로컬 창업에 관심 있는 청년',
    summary: '청년 창업가를 지역에 육성하고 생활인구 유입을 돕는 정책입니다.',
    detail: '로컬 창업 아이디어, 괴산군 정착 의향, 사업계획 확인이 필요합니다.',
    requiredDocuments: ['신청서', '사업계획서', '주민등록등본'],
    agency: '괴산군',
    sourceName: '충북 청년포털',
    sourceUrl: 'https://www.chungbuk.go.kr',
    lastChecked: '2026-08-11',
    status: '확인 필요',
    requiredInputs: ['age', 'region', 'startupInterest'],
  },
  {
    id: 'CB_STARTUP_001',
    title: '청년 소상공인 창업응원금 지원',
    category: '창업 지원',
    region: '충북 전역',
    benefit: '초기 창업 정착 지원',
    period: '공고 확인 필요',
    eligibility: '청년 창업자 또는 초기 소상공인',
    summary: '청년 창업기업의 초기 정착과 자생력 강화를 지원합니다.',
    detail: '창업 희망 여부, 사업자등록 여부, 창업 기간 확인이 필요합니다.',
    requiredDocuments: ['신청서', '사업자등록증', '사업계획서'],
    agency: '충청북도',
    sourceName: '충북 청년포털',
    sourceUrl: 'https://www.chungbuk.go.kr',
    lastChecked: '2026-08-11',
    status: '확인 필요',
    requiredInputs: ['age', 'startupInterest', 'businessRegistration'],
  },
];
