import { useState } from "react";
import { Check, MapPin, UserPlus } from "lucide-react";
import { Link, useLocation, useNavigate } from "react-router-dom";
import { useAuth } from "../context/AuthContext";
import { REGIONS } from "../data/mockData";
import type { UserProfile } from "../types";

export function LoginPage() {
  const { login } = useAuth();
  const navigate = useNavigate();
  const location = useLocation();
  const from = (location.state as { from?: string } | null)?.from || "/";
  const socialLogin = () => {
    // TODO(BE): 네이버·카카오 OAuth 인가 코드 교환 API로 교체
    login();
    navigate(from);
  };
  return <main className="min-h-[calc(100vh-72px)] bg-[linear-gradient(135deg,#f4faf6,#fff)]"><div className="mx-auto grid min-h-[620px] max-w-[1120px] items-center gap-20 px-6 lg:grid-cols-2"><section><span className="inline-flex items-center gap-2 rounded-full bg-brand-light px-3 py-1.5 text-xs font-bold text-brand"><MapPin size={13}/>충북 생활을 더 가깝게</span><h1 className="mt-5 text-3xl font-bold leading-[1.5]">로그인하고<br/><span className="text-brand">나의 정착 정보</span>를 이어서 확인하세요</h1><div className="mt-8 space-y-3">{["추천 결과와 관심 정책 저장","입력하던 시뮬레이션 이어하기","회원정보 기반 맞춤 분석"].map((item)=><div key={item} className="flex items-center gap-3 rounded-xl border border-emerald-100 bg-white p-4 text-sm shadow-card"><span className="flex h-6 w-6 items-center justify-center rounded-full bg-brand text-white"><Check size={13}/></span>{item}</div>)}</div></section><section className="rounded-2xl border border-stone-200 bg-white p-9 shadow-[0_18px_60px_rgba(15,92,52,.1)]"><p className="text-xs font-bold text-brand">WELCOME BACK</p><h2 className="mt-2 text-2xl font-bold">이메일 로그인</h2><label className="mt-7 block text-xs font-bold">이메일</label><input className="mt-2 h-12 w-full rounded-lg border border-stone-300 px-4 text-sm" defaultValue="user@example.com"/><label className="mt-4 block text-xs font-bold">비밀번호</label><input type="password" className="mt-2 h-12 w-full rounded-lg border border-stone-300 px-4 text-sm" defaultValue="password"/><button onClick={()=>{login();navigate(from);}} className="mt-6 w-full rounded-lg bg-brand py-3 text-sm font-bold text-white">로그인</button><div className="my-5 flex items-center gap-3"><span className="h-px flex-1 bg-stone-200"/><span className="text-[10px] text-stone-400">또는 간편 로그인</span><span className="h-px flex-1 bg-stone-200"/></div><div className="grid grid-cols-2 gap-2"><button onClick={socialLogin} className="flex items-center justify-center gap-2 rounded-lg border border-[#03C75A] py-2.5 text-xs font-semibold text-stone-700 transition-colors hover:bg-[#F2FFF7]"><span className="flex h-5 w-5 items-center justify-center rounded-sm bg-[#03C75A] text-[12px] font-black text-white">N</span>네이버 로그인</button><button onClick={socialLogin} className="flex items-center justify-center gap-2 rounded-lg border border-[#F5D900] bg-[#FEE500] py-2.5 text-xs font-semibold text-[#191919] transition-colors hover:bg-[#F8DE00]"><span className="relative flex h-5 w-5 items-center justify-center"><span className="h-3.5 w-[18px] rounded-[50%] bg-[#191919]"/><span className="absolute bottom-0.5 left-0.5 h-1.5 w-1.5 rotate-[-25deg] bg-[#191919]"/></span>카카오 로그인</button></div><p className="mt-3 text-center text-[10px] leading-4 text-stone-400">간편 로그인 계정 정보는 서비스 제공을 위해서만 사용됩니다.</p><p className="mt-6 text-center text-xs text-stone-400">계정이 없으신가요? <Link to="/signup" className="font-bold text-brand">회원가입</Link></p></section></div></main>;
}

const SIGNUP_STEPS = [
  [["age","나이",[]],["gender","성별",["여성","남성"]],["currentRegion","현재 거주지",[]]],
  [["major","전공",["공학계열","인문·사회","자연과학","예체능","기타"]],["job","직업 및 직무",["대학생","무직","IT·개발","제조·생산","사무·행정","교육·연구","서비스"]],["salary","현재 연봉",["소득 없음","2,400만원 미만","2,400~3,000만원","3,000~3,600만원","3,600~4,500만원","4,500~6,000만원","6,000만원 이상"]]],
  [["rent","월세 예산",["30만원 이하","30~40만원","40~50만원","50~60만원","60~80만원","80만원 이상","전세·매매 희망"]],["deposit","보증금 예산",["보증금 없음","500만원 이하","500~1,000만원","1,000~3,000만원","3,000~5,000만원","5,000만원 이상","아직 정하지 않음"]],["transport","이동수단",["자전거","버스","기차","자가용","기타","도보"]],["preferred","희망 지역",REGIONS]],
] as const;

export function SignupPage() {
  const { login, updateProfile } = useAuth();
  const navigate = useNavigate();
  const [step,setStep]=useState(0); const [form,setForm]=useState<Record<string,string>>({}); const [error,setError]=useState("");
  const next=()=>{if(SIGNUP_STEPS[step].some(([key])=>!form[key])){setError("필수 정보를 모두 입력해 주세요.");return;}setError("");setStep(step+1);};
  if(step===3)return <main className="flex min-h-[600px] items-center justify-center px-6"><section className="w-full max-w-lg rounded-2xl border border-stone-200 bg-white p-9 text-center"><UserPlus className="mx-auto text-brand" size={42}/><h1 className="mt-5 text-2xl font-bold">입력 정보 확인</h1><div className="mt-6 grid grid-cols-2 gap-2 text-left">{Object.entries(form).map(([key,value])=><div key={key} className="rounded-lg bg-stone-50 p-3"><small className="text-stone-400">{key}</small><b className="block text-xs">{value}</b></div>)}</div><button onClick={()=>{const profile={name:"신규 회원",email:"user@example.com",age:form.age,gender:form.gender,currentRegion:form.currentRegion,major:form.major,job:form.job,salary:form.salary,rent:form.rent,deposit:form.deposit,transport:form.transport,preferredRegions:[form.preferred],recommendRegion:false} satisfies UserProfile;updateProfile(profile);login();navigate("/mypage",{state:{signup:true}});}} className="mt-7 w-full rounded-lg bg-brand py-3 text-sm font-bold text-white">회원가입 완료하기</button></section></main>;
  return <main className="mx-auto max-w-[760px] px-6 py-9"><div className="flex justify-between">{["기본 정보","직업·소득","주거·이동","입력 확인"].map((label,index)=><div key={label} className="flex flex-1 items-center"><span className={`flex h-8 w-8 items-center justify-center rounded-full text-xs font-bold ${index<=step?"bg-brand text-white":"bg-stone-100 text-stone-400"}`}>{index+1}</span>{index<3&&<span className={`h-px flex-1 ${index<step?"bg-brand":"bg-stone-200"}`}/>}</div>)}</div><h1 className="mt-9 text-2xl font-bold">회원가입 정보 입력</h1><p className="mt-2 text-sm text-stone-500">정착 추천과 시뮬레이션에 필요한 필수 정보를 선택해 주세요.</p><section className="mt-6 space-y-7 rounded-2xl border border-stone-200 bg-white p-7">{SIGNUP_STEPS[step].map(([key,label,options])=><div key={key}><span className="mb-2 block text-xs font-bold">{label} <b className="text-rose-500">*</b></span>{options.length?<div className="flex flex-wrap gap-2">{options.map((option)=><button key={option} onClick={()=>setForm((current)=>({...current,[key]:option}))} className={`rounded-lg border px-4 py-2.5 text-xs font-bold ${form[key]===option?"border-brand bg-brand text-white":"border-stone-300 text-stone-600"}`}>{option}</button>)}</div>:<input type={key==="age"?"number":"text"} value={form[key]||""} onChange={(event)=>setForm((current)=>({...current,[key]:event.target.value}))} className="h-11 w-full rounded-lg border border-stone-300 px-3 text-sm" placeholder={key==="age"?"나이를 입력하세요":"현재 거주지를 입력하세요"}/>}</div>)}{error&&<p className="rounded-lg bg-rose-50 p-3 text-xs text-rose-600">{error}</p>}</section><div className="mt-5 flex justify-between"><button onClick={()=>step?setStep(step-1):navigate(-1)} className="rounded-lg border border-stone-300 px-5 py-2.5 text-sm">이전</button><button onClick={next} className="rounded-lg bg-brand px-6 py-2.5 text-sm font-bold text-white">다음</button></div></main>;
}
