import { useState } from "react";
import { Bookmark, ChevronRight, Edit3, MapPin, Trash2, UserRound } from "lucide-react";
import { Link, useLocation, useNavigate } from "react-router-dom";
import LoginRequired from "../components/LoginRequired";
import { useAuth } from "../context/AuthContext";
import { REGIONS } from "../data/mockData";

export function MyPage() {
  const { isLoggedIn, profile } = useAuth();
  const location = useLocation();
  if (!isLoggedIn) return <LoginRequired />;
  return <main className="mx-auto max-w-[1050px] px-6 py-9">{(location.state as {signup?:boolean}|null)?.signup&&<div className="mb-5 rounded-xl bg-brand p-4 text-sm font-bold text-white">회원가입이 완료되었습니다. 입력한 정보로 맞춤 정착 서비스를 이용할 수 있어요.</div>}<div className="flex items-center justify-between"><div><span className="text-xs font-bold text-brand">MY PAGE</span><h1 className="mt-2 text-3xl font-bold">{profile.name}님의 정착 정보</h1></div><Link to="/mypage/profile" className="flex items-center gap-2 rounded-lg border border-brand px-5 py-2.5 text-sm font-bold text-brand"><Edit3 size={15}/>회원정보 수정</Link></div><section className="mt-7 grid gap-5 md:grid-cols-[.7fr_1.3fr]"><div className="rounded-2xl border border-stone-200 bg-white p-6"><span className="flex h-14 w-14 items-center justify-center rounded-full bg-brand-light text-brand"><UserRound size={27}/></span><h2 className="mt-4 text-xl font-bold">{profile.name}</h2><p className="mt-1 text-xs text-stone-400">{profile.email}</p><div className="mt-5 border-t border-stone-100 pt-4 text-xs text-stone-500"><p>{profile.age} · {profile.gender}</p><p className="mt-2">{profile.currentRegion} 거주</p></div></div><div className="rounded-2xl border border-stone-200 bg-white p-6"><h2 className="text-lg font-bold">나의 정착 조건</h2><div className="mt-5 grid grid-cols-2 gap-3 md:grid-cols-3">{[["전공",profile.major],["직업·직무",profile.job],["현재 연봉",profile.salary],["월세 예산",profile.rent],["보증금 예산",profile.deposit||"아직 정하지 않음"],["이동수단",profile.transport],["희망 지역",profile.preferredRegions.join(", ")]].map(([label,value])=><div key={label} className="rounded-lg bg-stone-50 p-3"><span className="text-[9px] text-stone-400">{label}</span><b className="mt-1 block text-xs">{value}</b></div>)}</div></div></section><section className="mt-5 grid gap-4 md:grid-cols-3">{[["저장한 추천 지역","3곳",MapPin,"/recommendations"],["관심 정책","5개",Bookmark,"/policies"],["정보 다시 분석하기","조건 수정 후 실행",Edit3,"/mypage/profile"]].map(([title,value,Icon,path])=><Link to={String(path)} key={String(title)} className="flex items-center justify-between rounded-xl border border-stone-200 bg-white p-5"><div><Icon className="text-brand" size={20}/><p className="mt-3 text-xs text-stone-400">{String(title)}</p><b className="mt-1 block text-sm">{String(value)}</b></div><ChevronRight className="text-stone-300"/></Link>)}</section></main>;
}

export function ProfileEditPage() {
  const { isLoggedIn, profile, updateProfile } = useAuth();
  const navigate = useNavigate();
  const [form,setForm]=useState(profile);
  if (!isLoggedIn) return <LoginRequired />;
  const choices=[["gender",["여성","남성"]],["major",["공학계열","인문·사회","자연과학","예체능","기타"]],["job",["대학생","무직","IT·개발","제조·생산","사무·행정","교육·연구","서비스"]],["rent",["30만원 이하","30~40만원","40~50만원","50~60만원","60~80만원","80만원 이상","전세·매매 희망"]],["deposit",["보증금 없음","500만원 이하","500~1,000만원","1,000~3,000만원","3,000~5,000만원","5,000만원 이상","아직 정하지 않음"]],["transport",["자전거","버스","기차","자가용","기타","도보"]]] as const;
  return <main className="mx-auto max-w-[820px] px-6 py-9"><span className="text-xs font-bold text-brand">PROFILE EDIT</span><h1 className="mt-2 text-3xl font-bold">회원정보 수정</h1><p className="mt-2 text-sm text-stone-500">추천 결과의 조건 수정 버튼은 이 화면으로 연결됩니다.</p><section className="mt-7 space-y-7 rounded-2xl border border-stone-200 bg-white p-7"><div className="grid gap-4 md:grid-cols-2"><label><span className="mb-2 block text-xs font-bold">이름</span><input value={form.name} onChange={(e)=>setForm({...form,name:e.target.value})} className="h-11 w-full rounded-lg border border-stone-300 px-3 text-sm"/></label><label><span className="mb-2 block text-xs font-bold">현재 거주지</span><input value={form.currentRegion} onChange={(e)=>setForm({...form,currentRegion:e.target.value})} className="h-11 w-full rounded-lg border border-stone-300 px-3 text-sm"/></label></div>{choices.map(([key,options])=><div key={key}><span className="mb-2 block text-xs font-bold">{{gender:"성별",major:"전공",job:"직업 및 직무",rent:"월세 예산",deposit:"보증금 예산",transport:"이동수단"}[key]}</span><div className="flex flex-wrap gap-2">{options.map((option)=><button key={option} onClick={()=>setForm({...form,[key]:option})} className={`rounded-lg border px-4 py-2.5 text-xs font-bold ${form[key]===option?"border-brand bg-brand text-white":"border-stone-300"}`}>{option}</button>)}</div></div>)}<div><span className="mb-2 block text-xs font-bold">희망 지역 (복수 선택)</span><div className="flex flex-wrap gap-2">{REGIONS.map((region)=><button key={region} onClick={()=>setForm({...form,preferredRegions:form.preferredRegions.includes(region)?form.preferredRegions.filter((item)=>item!==region):[...form.preferredRegions,region]})} className={`rounded-lg border px-3 py-2 text-xs ${form.preferredRegions.includes(region)?"border-brand bg-brand-light text-brand":"border-stone-300"}`}>{region}</button>)}</div></div></section><div className="mt-5 flex justify-end gap-2"><button onClick={()=>navigate(-1)} className="rounded-lg border border-stone-300 px-5 py-2.5 text-sm">취소</button><button onClick={()=>{updateProfile(form);navigate("/mypage");}} className="rounded-lg bg-brand px-6 py-2.5 text-sm font-bold text-white">저장하기</button></div></main>;
}

export function SavedItemsPage() {
  const { isLoggedIn } = useAuth();
  if (!isLoggedIn) return <LoginRequired />;
  return <main className="mx-auto max-w-[1050px] px-6 py-9"><div><span className="text-xs font-bold text-brand">SAVED ITEMS</span><h1 className="mt-2 text-3xl font-bold">저장한 지역 및 정책</h1><p className="mt-2 text-sm text-stone-500">내 정보와 분리된 보관함에서 관심 항목을 관리할 수 있습니다.</p></div><div className="mt-7 grid gap-6 lg:grid-cols-2"><section className="rounded-2xl border border-stone-200 bg-white p-6"><div className="flex items-center justify-between"><h2 className="flex items-center gap-2 text-lg font-bold"><MapPin className="text-brand"/>저장한 지역</h2><span className="text-xs text-stone-400">3곳</span></div><div className="mt-5 space-y-3">{["청주시 오창읍","진천·음성 충북혁신도시","충주시 연수동"].map((item,index)=><div key={item} className="flex items-center rounded-xl border border-stone-100 p-4"><span className="flex h-9 w-9 items-center justify-center rounded-full bg-brand-light text-xs font-bold text-brand">{index+1}</span><div className="ml-3"><b className="text-sm">{item}</b><p className="mt-1 text-[10px] text-stone-400">추천 적합도 {94-index*5}점</p></div><button className="ml-auto text-stone-300 hover:text-rose-500" aria-label={`${item} 삭제`}><Trash2 size={16}/></button></div>)}</div></section><section className="rounded-2xl border border-stone-200 bg-white p-6"><div className="flex items-center justify-between"><h2 className="flex items-center gap-2 text-lg font-bold"><Bookmark className="text-brand"/>저장한 정책</h2><span className="text-xs text-stone-400">3개</span></div><div className="mt-5 space-y-3">{["충북 청년 월세 지원","지역주도형 청년일자리 정착지원","청년 로컬창업 패키지"].map((item)=><div key={item} className="flex items-center rounded-xl border border-stone-100 p-4"><span className="flex h-9 w-9 items-center justify-center rounded-full bg-brand-light text-brand"><Bookmark size={15}/></span><div className="ml-3"><b className="text-sm">{item}</b><p className="mt-1 text-[10px] text-stone-400">신청 정보 확인 필요</p></div><button className="ml-auto text-stone-300 hover:text-rose-500" aria-label={`${item} 삭제`}><Trash2 size={16}/></button></div>)}</div></section></div></main>;
}
